from turtle import *


ht()
command = ""
w=first_angle = ""
r=second_angle=""
while command not in ["end", "exit", "back", "finish","payan"]:
    command = textinput("Command", "Enter command: ")
    if command in ["circle", "dayere"]:
        d = numinput("Circle angle", "Enter circle angle: ")
        r = numinput("Radius", "Enter radius: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("Pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        begin_fill()
        fillcolor(c)
        circle (r, d)
        end_fill()
        

    elif command in ["square", "moraba"]:
        a = numinput("Width", "Enter width: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (4):
            fd(a)
            lt(90)
        end_fill()
    elif command in ["rectangle", "mostatil"]:
        b = numinput("Width", "Enter width: ")
        z = numinput("Height", "Enter height: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (2):
            fd(b)
            lt(90)
            fd(z)
            lt(90)
        end_fill()
    elif command in ("hexagon", "shesh zelei"):
        l = numinput("Side", "Enter side: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (8):
            fd(l)
            lt(360/6)
        end_fill()
    elif command in ("triangle", "mosallas"):
        m = numinput("Side", "Enter side: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (3):
            fd(m)
            lt(120)
        end_fill()
    elif command in ("pentagon", "panj zelei"):
        q = numinput("Side", "Enter side: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (5):
            fd(q)
            lt(360/5)
        end_fill()
    elif command in ("parallelogram", "lozy montazem"):
        o = numinput("width", "Enter width: ")
        z = numinput("Height", "Enter height: ")
        h = numinput("Angle", "Enter first angle: ")
        j = numinput("Angle", "Enter second angle: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (2):
            fd(o)
            lt(60)
            fd(z)
            lt(120)
        end_fill()
    elif command in ("star", "setare"):
        o = numinput("side", "Enter side: ")
        c = textinput("Fill color", "Enter fill color: ")
        p = textinput("pen color", "Enter pen color: ")
        s = numinput("Pen size", "Enter pen size: ")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pensize(s)
        pencolor(p)
        fillcolor(c)
        begin_fill()
        for i in range (6):
            lt(-120)
            fd(o)
            lt(120)
            fd(o)
            lt(60)
        end_fill()
    elif command in ("title", "mozo"):
        ac = textinput("Title", "Enter title")
        aa = numinput("Size", "Enter size: ")
        an = textinput("Pencolor", "Enter pencolor")
        x = numinput("X", "Enter X: ")
        y = numinput("Y", "Enter Y: ")
        up()
        goto(x, y)
        down()
        pencolor(an)
        write(ac, font=(aa))
    elif command in ("fd", "forward"):
        ab = numinput("Forward", "Enter forward")
        ae = textinput("Pen color", "Enter pen color: ")
        af = numinput("Size", "Enter pen size: ")
        pencolor(ae)
        pensize(af)
        fd(ab)
    elif command in ("lt", "left"):
        ad = numinput("Left", "Enter left")
        lt(ad)
    elif command in ("rt", "right"):
        ad = numinput("Right", "Enter right")
        rt(ad)
    elif command in ("bk", "backward"):
        ab = numinput("Backward", "Enter backward")
        ae = textinput("Pen color", "Enter pen color: ")
        af = numinput("Size", "Enter pen size: ")
        pencolor(ae)
        pensize(af)
        bk(ab)
    elif command in ("up", "penup"):
        up()
        aj = numinput("X", "Enter X: ")
        ak = numinput("Y", "Enter Y")
        goto(aj, ak)
        down()
    elif command in ("clear"):
        clear()
    elif command not in ("end", "exit", "back", "finish","payan", "pentagon", "panj zelei", "triangle", "mosallas", "hexagon", "shesh zelei", "rectangle", "mostatil", "square", "moraba", "circle", "dayere", "star", "setare", "parallelogram", "lozy montazem", "title", "mozo", "fd", "forward", "lt", "left", "clear", "rt", "right", "bk", "backward"):
        up()
        goto(-350, 300)
        down
        pencolor("black")
        write("Command is not correct! ", font= ("Times New Roman", "10", "bold"))
done()