from turtle import *
hideturtle()
speed(10)
a = numinput('width', 'Enter width: ')
b = numinput('height', 'Enter height: ')
c = textinput('color', 'Enter color: ')
x = numinput('x', 'x:')
y = numinput('y', 'y: ')
up()
goto(x, y)
down()
begin_fill()
fillcolor(c)
fd(a)
lt(90)
fd(b)
lt(90)
fd(a)
lt(90)
fd(b)
end_fill()
done()